.TH SHRONK\-CLI\-UTILS 1 11-12-2022 GNU
.SH NAME
\fBshronk\-cli\-utils\fR \- Some of my personal tools for general use on arch linux\.
.SH SYNOPSIS
\fBmkservice\fR \- This is a quick tool to make services\.
.P
\fBbackup\fR \- A tool to create backups\.
.SH DESCRIPTION
This is just a set of tools that I have made to make my life easier when using arch linux I just want to share these with people online\.
